"""campo cpf

Revision ID: 4fa0fe99a49f
Revises: 873e1f996613
Create Date: 2023-08-04 13:42:03.723677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa0fe99a49f'
down_revision = '873e1f996613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_sanguineo', sa.String(length=5), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Volunteer', schema=None) as batch_op:
        batch_op.drop_column('tipo_sanguineo')

    # ### end Alembic commands ###
