"""campo cpf

Revision ID: 873e1f996613
Revises: c2e5ec3b814d
Create Date: 2023-08-04 00:04:10.548833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873e1f996613'
down_revision = 'c2e5ec3b814d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf_cnpj', sa.String(length=14), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Volunteer', schema=None) as batch_op:
        batch_op.drop_column('cpf_cnpj')

    # ### end Alembic commands ###
