"""campo number

Revision ID: c2e5ec3b814d
Revises: 
Create Date: 2023-08-03 23:19:21.499745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e5ec3b814d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.String(length=60), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Volunteer', schema=None) as batch_op:
        batch_op.drop_column('number')

    # ### end Alembic commands ###
